@extends('layouts.app')
@section('title', $model->exists ? 'აღსაზრდელის რედაქტირება' : 'ახალი აღსაზრდელი')
@section('content')
<x-ui.page-header eyebrow="აღსაზრდელთა მართვა" :title="$model->exists ? 'აღსაზრდელის რედაქტირება' : 'ახალი აღსაზრდელი'" description="შეავსეთ ბავშვის, მშობლისა და განთავსების აუცილებელი ინფორმაცია." />
<x-ui.page><div class="record-layout">
  <form method="POST" action="{{ route('kindergarteners.store') }}" class="card">@csrf<input type="hidden" name="id" value="{{ $model->id }}">
    <div class="card-header"><div><h3 class="card-title">ძირითადი ინფორმაცია</h3><span class="kids-list-caption">ვარსკვლავით მონიშნული ველები სავალდებულოა</span></div></div>
    <div class="card-body">
      <div class="form-section"><div class="form-section__title"><span><i class="fas fa-child"></i></span><div><h2>ბავშვის მონაცემები</h2><p>იდენტიფიკაცია და დაბადების თარიღი</p></div></div><div class="form-grid form-grid--three"><div class="form-group"><label for="kids_personal_number">პირადი ნომერი *</label><input id="kids_personal_number" name="kids_personal_number" value="{{ old('kids_personal_number',$model->kids_personal_number) }}" class="form-control" inputmode="numeric" maxlength="11" required></div><div class="form-group"><label for="kids_first_name">სახელი *</label><input id="kids_first_name" name="kids_first_name" value="{{ old('kids_first_name',$model->kids_first_name) }}" class="form-control" required></div><div class="form-group"><label for="kids_last_name">გვარი *</label><input id="kids_last_name" name="kids_last_name" value="{{ old('kids_last_name',$model->kids_last_name) }}" class="form-control" required></div><div class="form-group"><label for="birth_date">დაბადების თარიღი *</label><input id="birth_date" type="date" name="birth_date" value="{{ old('birth_date',$model->birth_date) }}" class="form-control" required></div></div></div>
      <div class="form-section"><div class="form-section__title"><span><i class="fas fa-female"></i></span><div><h2>დედის ინფორმაცია</h2><p>საკონტაქტო პირის მონაცემები</p></div></div><div class="form-grid form-grid--three"><div class="form-group"><label>პირადი ნომერი</label><input name="mother_personal_number" value="{{ old('mother_personal_number',$model->mother_personal_number) }}" class="form-control" inputmode="numeric" maxlength="11"></div><div class="form-group"><label>სახელი</label><input name="mother_first_name" value="{{ old('mother_first_name',$model->mother_first_name) }}" class="form-control"></div><div class="form-group"><label>გვარი</label><input name="mother_last_name" value="{{ old('mother_last_name',$model->mother_last_name) }}" class="form-control"></div></div></div>
      <div class="form-section"><div class="form-section__title"><span><i class="fas fa-male"></i></span><div><h2>მამის ინფორმაცია</h2><p>დამატებითი საკონტაქტო პირი</p></div></div><div class="form-grid form-grid--three"><div class="form-group"><label>პირადი ნომერი</label><input name="father_personal_number" value="{{ old('father_personal_number',$model->father_personal_number) }}" class="form-control" inputmode="numeric" maxlength="11"></div><div class="form-group"><label>სახელი</label><input name="father_first_name" value="{{ old('father_first_name',$model->father_first_name) }}" class="form-control"></div><div class="form-group"><label>გვარი</label><input name="father_last_name" value="{{ old('father_last_name',$model->father_last_name) }}" class="form-control"></div></div></div>
      <div class="form-section"><div class="form-section__title"><span><i class="fas fa-address-book"></i></span><div><h2>კონტაქტი და განთავსება</h2><p>შეტყობინებებისა და ჯგუფის ინფორმაცია</p></div></div><div class="form-grid form-grid--two"><div class="form-group"><label for="mobile_number">მობილური ნომერი *</label><div class="input-group"><span class="input-group-text">+995</span><input id="mobile_number" name="mobile_number" value="{{ old('mobile_number',$model->mobile_number) }}" class="form-control" inputmode="numeric" maxlength="9" required></div></div><div class="form-group"><label for="email">ელფოსტა (არასავალდებულო)</label><input id="email" type="email" name="email" value="{{ old('email',$model->email) }}" class="form-control"></div>
      @if(auth()->user()->isUnionAdmin())<div class="form-group"><label for="municipalities">მუნიციპალიტეტი *</label><select id="municipalities" name="municipality_id" class="custom-select" required><option value="">აირჩიეთ მუნიციპალიტეტი</option></select></div><div class="form-group"><label for="kindergartens">ბაღი *</label><select id="kindergartens" name="kindergarten_id" class="custom-select" required><option value="">აირჩიეთ ბაღი</option></select></div>@else<input type="hidden" name="municipality_id" value="{{ data_get($data,'assigned_garden.municipality_id') }}"><input type="hidden" name="kindergarten_id" value="{{ data_get($data,'assigned_garden.id') }}"><div class="assigned-garden"><span><i class="fas fa-school"></i></span><div><small>მინიჭებული ბაღი</small><strong>{{ data_get($data,'assigned_garden.name') }}</strong></div></div>@endif
      <div class="form-group"><label for="group_id">ასაკობრივი ჯგუფი *</label><select id="group_id" name="group_id" class="custom-select" required><option value="">აირჩიეთ ჯგუფი</option>@foreach($data['group_ranges'] as $id=>$range)<option value="{{$id}}" @selected((string)old('group_id',$model->group_id)===(string)$id)>{{$range}}</option>@endforeach</select></div></div></div>
      @if(auth()->user()->isUnionAdmin())<div class="form-section"><div class="form-section__title"><span><i class="fas fa-star"></i></span><div><h2>პრიორიტეტი</h2><p>პრიორიტეტს საბოლოოდ გაერთიანების ადმინისტრაცია ადასტურებს</p></div></div><div class="form-grid form-grid--two"><div class="form-group"><label for="priority_id">პრიორიტეტის ტიპი</label><select id="priority_id" name="priority_id" class="custom-select"><option value="">არ სარგებლობს</option>@foreach($data['priorities'] as $id=>$priority)<option value="{{$id}}" @selected((string)old('priority_id',optional($model->priority)->priority_id)===(string)$id)>{{$priority}}</option>@endforeach</select></div><div class="form-group"><label for="has_permission">პრიორიტეტის დასტური</label><select id="has_permission" name="has_permission" class="custom-select"><option value="0" @selected(!old('has_permission',optional($model->priority)->has_permission))>დაუდასტურებელი</option><option value="1" @selected(old('has_permission',optional($model->priority)->has_permission))>დადასტურებული</option></select></div></div></div>@endif
    </div><div class="card-footer modern-card-footer"><a href="{{ route('kindergarteners.index') }}" class="btn btn-secondary"><x-admin-icon name="arrow-left" /> გაუქმება</a><button type="submit" class="btn btn-primary"><x-admin-icon name="save" /> შენახვა</button></div>
  </form>
  <aside class="record-aside"><div class="record-status"><small>მიმდინარე სტატუსი</small><strong class="application-status application-status--{{ $model->exists && in_array($model->application_status, ['registered','waiting','enrolled','suspended','cancelled'], true) ? $model->application_status : 'neutral' }}">{{ $model->exists ? $model->application_status_label : 'ახალი განაცხადი' }}</strong></div><div class="record-help"><i class="fas fa-info-circle"></i><p>ადგილის არსებობისას ახალი განაცხადი ჩაირიცხება, ხოლო შევსებულ ჯგუფში ავტომატურად მოხვდება მომლოდინეთა რიგში.</p></div>@if($model->exists)<dl><div><dt>ბაღი</dt><dd>{{ optional($model->kindergarten)->name ?: data_get($data,'assigned_garden.name','—') }}</dd></div><div><dt>რეგისტრაცია</dt><dd>{{ optional($model->created_at)->format('d.m.Y H:i') }}</dd></div></dl>@endif</aside>
</div></x-ui.page>
@endsection
@push('scripts')
@if(auth()->user()->isUnionAdmin())<script nonce="{{ $cspNonce }}">(function(){const model=@json($model),municipalities=@json($data['municipalities']),municipalitySelect=document.getElementById('municipalities'),gardenSelect=document.getElementById('kindergartens');function gardensFor(id){gardenSelect.innerHTML='<option value="">აირჩიეთ ბაღი</option>';const municipality=municipalities.find(item=>String(item.id)===String(id));(municipality?.kindergartens||[]).forEach(garden=>gardenSelect.add(new Option(garden.name,garden.id)));const selected='{{ old('kindergarten_id',$model->kindergarten_id) }}';if(selected)gardenSelect.value=selected;}municipalities.forEach(item=>municipalitySelect.add(new Option(item.name,item.id)));municipalitySelect.value='{{ old('municipality_id',$model->municipality_id) }}';gardensFor(municipalitySelect.value);municipalitySelect.addEventListener('change',event=>gardensFor(event.target.value));})();</script>@endif
@endpush
