@extends('layouts.app')
@section('title','ოპერაციების კონტროლი')
@section('content')
<div class="content-header modern-page-header"><div class="container-fluid"><div class="page-heading-row"><div><span class="dashboard-eyebrow">რიგი და შეტყობინებები</span><h1>ოპერაციების კონტროლი</h1><p>აკონტროლეთ მომლოდინეთა რიგი, ადგილის შეთავაზებები და მშობლის ელფოსტის მიწოდება.</p></div><form method="POST" action="{{route('operations.process-waiting-list')}}">@csrf<button class="btn btn-primary"><i class="fas fa-sync"></i> რიგის დამუშავება ახლა</button></form></div></div></div>
<section class="content"><div class="row"><div class="col-md-3"><div class="small-box bg-info"><div class="inner"><h3>{{(int)($capacity->total??0)}}</h3><p>სრული ტევადობა</p></div></div></div><div class="col-md-3"><div class="small-box bg-success"><div class="inner"><h3>{{(int)($capacity->filled??0)}}</h3><p>დაკავებული</p></div></div></div><div class="col-md-3"><div class="small-box bg-warning"><div class="inner"><h3>{{(int)($capacity->reserved??0)}}</h3><p>დაჯავშნილი</p></div></div></div><div class="col-md-3"><div class="small-box bg-primary"><div class="inner"><h3>{{$waiting->total()}}</h3><p>აქტიური რიგი</p></div></div></div></div>
<div class="card"><div class="card-header"><h3 class="card-title">მომლოდინეთა რიგი</h3></div><div class="card-body table-responsive"><table class="table table-hover"><thead><tr><th>ბავშვი</th><th>ბაღი</th><th>ჯგუფი</th><th>პრიორიტეტი</th><th>რიგშია</th><th>მდგომარეობა</th></tr></thead><tbody>@forelse($waiting as $item)<tr><td>{{optional($item->kindergartener)->kids_first_name}} {{optional($item->kindergartener)->kids_last_name}}</td><td>{{optional($item->kindergarten)->name}}</td><td>{{optional($item->groupRange)->range}}</td><td>{{$item->priority_rank===999?'ჩვეულებრივი':$item->priority_rank}}</td><td>{{optional($item->queued_at)->format('d.m.Y H:i')}}</td><td><span class="badge badge-{{$item->state==='offered'?'warning':'secondary'}}">{{$item->state==='offered'?'შეთავაზებულია':'მომლოდინე'}}</span></td></tr>@empty<tr><td colspan="6">აქტიური რიგი ცარიელია.</td></tr>@endforelse</tbody></table></div><div class="card-footer">{{$waiting->appends(request()->except('waiting_page'))->links()}}</div></div>
<div class="card"><div class="card-header"><h3 class="card-title">ადგილის შეთავაზებები</h3></div><div class="card-body table-responsive"><table class="table table-hover"><thead><tr><th>ბავშვი</th><th>შექმნილია</th><th>ვადა</th><th>პასუხი</th></tr></thead><tbody>@forelse($offers as $offer)<tr><td>{{optional(optional($offer->entry)->kindergartener)->kids_first_name}} {{optional(optional($offer->entry)->kindergartener)->kids_last_name}}</td><td>{{$offer->created_at->format('d.m.Y H:i')}}</td><td>{{$offer->expires_at->format('d.m.Y H:i')}}</td><td>{{$offer->response ? ['accepted'=>'მიღებული','declined'=>'უარყოფილი','expired'=>'ვადაგასული'][$offer->response]??$offer->response : 'პასუხის მოლოდინში'}}</td></tr>@empty<tr><td colspan="4">შეთავაზებები არ არის.</td></tr>@endforelse</tbody></table></div><div class="card-footer">{{$offers->appends(request()->except('offers_page'))->links()}}</div></div>
<div class="card"><div class="card-header"><h3 class="card-title">ელფოსტის მიწოდების ჟურნალი</h3></div><div class="card-body table-responsive"><table class="table table-hover"><thead><tr><th>ბავშვი</th><th>მოვლენა</th><th>სტატუსი</th><th>მცდელობა</th><th>გაგზავნილია</th><th>შეცდომა</th></tr></thead><tbody>@forelse($notifications as $delivery)<tr><td>{{optional($delivery->kindergartener)->kids_first_name}} {{optional($delivery->kindergartener)->kids_last_name}}</td><td>{{$delivery->event}}</td><td>{{$delivery->status}}</td><td>{{$delivery->attempts}}</td><td>{{optional($delivery->sent_at)->format('d.m.Y H:i')?:'—'}}</td><td>{{$delivery->last_error?:'—'}}</td></tr>@empty<tr><td colspan="6">შეტყობინებები არ არის.</td></tr>@endforelse</tbody></table></div><div class="card-footer">{{$notifications->appends(request()->except('notifications_page'))->links()}}</div></div></section>
@endsection
