@extends('layouts.app')
@section('content')
<div class="content-header modern-page-header"><div class="container-fluid"><div class="page-heading-row"><div><span class="dashboard-eyebrow">სასწავლო წლის გადასვლა</span><h1>პორტირების წინასწარი შემოწმება</h1><p>შედეგი მხოლოდ წინასწარი გათვლაა — ამ გვერდზე არცერთი ბავშვის მონაცემი და ტევადობა არ იცვლება.</p></div><a href="{{route('settings.index')}}#annual-porting" class="btn btn-light">უკან პორტირებაზე</a></div></div></div>
<section class="content porting-preview-page">
  <div class="summary-strip"><div><span class="summary-icon"><i class="fas fa-exchange-alt"></i></span><span><small>გადავა შემდეგ ჯგუფში</small><strong>{{$preview['moves_total']}}</strong></span></div><div><span class="summary-icon summary-icon--navy"><i class="fas fa-graduation-cap"></i></span><span><small>დაამთავრებს ბაღს</small><strong>{{$preview['graduates_total']}}</strong></span></div><div><span class="summary-icon summary-icon--coral"><i class="fas fa-exclamation-triangle"></i></span><span><small>ადგილის დეფიციტი</small><strong>{{$preview['shortages']->count()}}</strong></span></div><div><span class="summary-icon summary-icon--amber"><i class="fas fa-tools"></i></span><span><small>გასასწორებელი საკითხი</small><strong>{{count($preview['errors'])}}</strong></span></div></div>
  @if(count($preview['errors']))<div class="alert alert-warning"><strong><i class="fas fa-exclamation-triangle"></i> პორტირების დაწყებამდე საჭიროა გასწორება</strong><ul class="mb-0 mt-2">@foreach($preview['errors'] as $error)<li>{{$error}}</li>@endforeach</ul></div>@else<div class="alert alert-success"><i class="fas fa-check-circle"></i> წინასწარი შემოწმებით პორტირების შემაფერხებელი პრობლემა არ იძებნება.</div>@endif
  <div class="card"><div class="card-header"><h3 class="card-title">შემდეგ ჯგუფში გადასაყვანი ბავშვები</h3></div><div class="card-body table-responsive"><table class="table table-hover"><thead><tr><th>ბავშვი</th><th>ბაღი</th><th>მიმდინარე ჯგუფი</th><th>შემდეგი ჯგუფი</th></tr></thead><tbody>@forelse($preview['moves'] as $row)<tr><td>{{$row->name}}</td><td>{{$row->kindergarten}}</td><td>{{$row->from}} წ.</td><td>{{$row->to}} წ.</td></tr>@empty<tr><td colspan="4" class="text-center text-muted py-4">გადასაყვანი ბავშვი არ არის.</td></tr>@endforelse</tbody></table></div><div class="card-footer">{{$preview['moves']->links()}}</div></div>
  <div class="card"><div class="card-header"><div><h3 class="card-title">ბაღს დაასრულებენ</h3><p class="text-muted mb-0 mt-1 small">ბავშვები, რომლებიც პორტირების შესრულების შემდეგ მიიღებენ „დამთავრებულის“ სტატუსს და გათავისუფლდება მათი ადგილი.</p></div></div><div class="card-body table-responsive"><table class="table table-hover"><thead><tr><th>ბავშვი</th><th>ბაღი</th><th>ბოლო ჯგუფი</th></tr></thead><tbody>@forelse($preview['graduates'] as $row)<tr><td>{{$row->name}}</td><td>{{$row->kindergarten}}</td><td>{{$row->group}} წ.</td></tr>@empty<tr><td colspan="3" class="text-center text-muted py-4">დამამთავრებელი ჯგუფის ბავშვი არ არის.</td></tr>@endforelse</tbody></table></div><div class="card-footer">{{$preview['graduates']->links()}}</div></div>
  <div class="card"><div class="card-header"><h3 class="card-title">სად არ იქნება საკმარისი ადგილი</h3></div><div class="card-body table-responsive"><table class="table table-hover"><thead><tr><th>ბაღი</th><th>სამიზნე ჯგუფი</th><th>საჭირო ადგილი</th><th>ზღვარი</th><th>დეფიციტი</th></tr></thead><tbody>@forelse($preview['shortages'] as $row)<tr><td>{{$row->kindergarten}}</td><td>{{$row->group}} წ.</td><td>{{$row->needed}}</td><td>{{$row->capacity}}</td><td><span class="analytics-state analytics-state--full">{{$row->shortage}}</span></td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-4">ადგილის დეფიციტი არ იძებნება.</td></tr>@endforelse</tbody></table></div></div>
</section>
@endsection
